resource_group_name = "rg-retail-project"
location            = "West US 2"
server_name         = "pocserver999"
database_name       = "pocdatabase"
admin_username      = "adminuser"
admin_password      = "India@123"
workload_env        = "Development"
